apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-kube-deployment
spec:
  selector:
    matchLabels:
      app: my-nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      imagePullSecrets:
        - name: mydockerhub
      containers:
        - name: my-nginx-container
          image: mikejc30/jenkins-kube:latest
          ports:
            - containerPort: 80
