apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
spec:
  selector:
    matchLabels:
      app: my-nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: my-nginx-app
    spec:
      containers:
        - name: my-nginx-container
          image: mikejc30/my-nginx-image:latest
          ports:
            - containerPort: 80
