apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8
spec:
  selector:
    matchLabels:
      app: nginx-app
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      imagePullSecrets:
        - name: mydockerhub
      containers:
        - name: nginx-container
          image: mikejc30/k8:latest
          ports:
            - containerPort: 80
